### ISSUE TITLE
Version advance for no reasen [Question]

### ISSUE THREAD

**Issue by Finii** [taskolib/libgit4cpp#25]
I'm not sure
* Why do we have so many new versions, with no change at all (except the version number change)
* Why are there always two commits that do 'the same', they could have been squashed?

![image](https://github.com/user-attachments/assets/3008bd10-158c-44b2-b6fc-5dc92ee5a300)

**Comment by alt-graph** [comment]
The new versions are necessary to build distinct Debian packages for each new DOOCS release (at least I think they are necessary). The reason for this is that each DOOCS release comes with a new GUL package, which `libgit4cpp` depends on and links to, and higher-level software like `doocs-taskomatlib` links to that new GUL version too. That is a diamond dependency, so we have to make sure everyone uses the same GUL at the bottom.

As for the two commits per version, I think that comes from a) a manual commit and b) an automatic commit by `makeDdeb`. I can try to do that in a smarter way.

**Comment by Finii** [comment]
Thanks for answering!
That reminds me that I wanted to resolve the diamond; I already had an idea, but where is it?
